// Color Scheme generated by http://colorschemedesigner.com/csd-3.5/
const backgroundColors = [
  '#FFD773',
  '#FF8373',
  '#707ED7',
  '#64DF85',
];

const backgroundDivs = document.querySelectorAll('.full-width-background');

function distanceToTop(e) {
  return e.getBoundingClientRect().top;
}

function closestToTop(elements) {
  let minimumNonNegativeDistanceToTop = 9999;
  let index = 0;

  elements.forEach(function(e, i) {
    let distance = distanceToTop(e);

    if (distance > -20 && distance < minimumNonNegativeDistanceToTop) {
      minimumNonNegativeDistanceToTop = distance;
      index = i;
    }
  });

  return elements[index];
}

function takeRandom(array) {
  const randomIndex = Math.floor(Math.random() * array.length);
  return array[randomIndex];
}

let pause = false;

window.addEventListener('scroll', function(e) {
  if (pause) {
    return;
  }

  pause = true;
  setTimeout(() => { pause = false }, 1500);

  const divInViewport = closestToTop(backgroundDivs);

  backgroundDivs.forEach(function(div) {
    div.style.backgroundColor = '#FFFFFF';
  });

  divInViewport.style.backgroundColor = takeRandom(backgroundColors);
});
