function backgroundColorAnimation() {
  // Color Scheme generated by http://colorschemedesigner.com/csd-3.5/
  const backgroundColors = [
    '#FFD773',
    '#FF8373',
    '#707ED7',
    '#64DF85',
  ];

  const backgroundDivs = document.querySelectorAll('.full-width-background');

  function distanceToTop(e) {
    const { top, bottom } = e.getBoundingClientRect();
    return (top + bottom) / 2;
  }

  function closestToTop(elements) {
    let minimumNonNegativeDistanceToTop = 9999;
    let index = 0;

    elements.forEach(function(e, i) {
      let distance = distanceToTop(e);

      if (distance > 0 && distance < minimumNonNegativeDistanceToTop) {
        minimumNonNegativeDistanceToTop = distance;
        index = i;
      }
    });

    return elements[index];
  }

  function randomIndex(array) {
    return Math.floor(Math.random() * array.length);
  }

  let pause = false;
  let previousColor = null;

  function pickNewColor(prevColor) {
    const newColorIndex = randomIndex(backgroundColors);

    if (backgroundColors[newColorIndex] !== prevColor) {
      return backgroundColors[newColorIndex];
    }

    return backgroundColors[newColorIndex + 1] || backgroundColors[newColorIndex - 1];
  }

  function animateBackgroundDivColor() {
    if (pause) {
      return;
    }

    pause = true;
    setTimeout(() => { pause = false }, 1000);

    const divInViewport = closestToTop(backgroundDivs);

    backgroundDivs.forEach(function(div) {
      div.style.backgroundColor = '#FFFFFF';
    });

    const newColor = pickNewColor(previousColor);
    divInViewport.style.backgroundColor = newColor;
    previousColor = newColor;
  }

  window.addEventListener('DOMContentLoaded', setTimeout(animateBackgroundDivColor, 500));
  window.addEventListener('mousewheel', animateBackgroundDivColor);
  window.addEventListener('MozMousePixelScroll', animateBackgroundDivColor);
}

backgroundColorAnimation();

function registerLinkEventHandlers() {
  const newPageLinks = document.querySelectorAll('.new-page');
  newPageLinks.forEach(function(link) {
    link.addEventListener('click', function(e) {
      e.preventDefault();

      return fetch(`/${link.dataset.page}.html`)
        .then(res => res.text())
        .then(function(html) {
          document.querySelector('main').innerHTML = html;
          registerLinkEventHandlers();
          backgroundColorAnimation();
        })
        .catch(e => console.error(e.message));
    });
  });
}

registerLinkEventHandlers();
